language: android
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
before_script:
  - chmod +x gradlew
script:
 - ./gradlew assembleDebug
 - ./gradlew testDebug
