language: android
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-23.0.0
    - android-23
    - extra-android-m2repository
before_install:
 - chmod +x gradlew
script:
 - ./gradlew assembleDebug
 - ./gradlew testDebug