[versions]
android = "7.3.0"
android-desugar = "1.1.8"
androidx-appcompat = "1.5.1"
androidx-cardview = "1.0.0"
androidx-preference = "1.1.1"
androidx-recyclerview = "1.2.1"
dagger = "2.43.2"
material = "1.6.1"
materialdialogs = "0.9.6.0"
okhttp = "3.9.0"
preferencex = "1.1.0"
retrofit = "2.3.0"
rxandroid = "1.2.1"
rxbinding = "1.0.1"
rxjava = "1.2.7"
rxlifecycle = "1.0"
rxpreferences = "1.0.2"
timber = "4.5.1"

[libraries]
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-desugar" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
dagger-hilt-android-runtime = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
material = { module = "com.google.android.material:material", version.ref = "material" }
materialdialogs = { module = "com.afollestad.material-dialogs:core", version.ref = "materialdialogs" }
materialdialogs-commons = { module = "com.afollestad.material-dialogs:commons", version.ref = "materialdialogs" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logginginterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
preferencex = { module = "com.takisoft.preferencex:preferencex", version.ref = "preferencex" }
preferencex-datetimepicker = { module = "com.takisoft.preferencex:preferencex-datetimepicker", version.ref = "preferencex" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-adapter-rxjava = { module = "com.squareup.retrofit2:adapter-rxjava", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
rxandroid = { module = "io.reactivex:rxandroid", version.ref = "rxandroid" }
rxbinding = { module = "com.jakewharton.rxbinding:rxbinding", version.ref = "rxbinding" }
rxbinding-appcompat = { module = "com.jakewharton.rxbinding:rxbinding-appcompat-v7", version.ref = "rxbinding" }
rxjava = { module = "io.reactivex:rxjava", version.ref = "rxjava" }
rxlifecycle = { module = "com.trello:rxlifecycle", version.ref = "rxlifecycle" }
rxlifecycle-components = { module = "com.trello:rxlifecycle-components", version.ref = "rxlifecycle" }
rxpreferences = { module = "com.f2prateek.rx.preferences:rx-preferences", version.ref = "rxpreferences" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
