[versions]
android = "7.3.0"
androidx-activity = "1.5.1"
dagger = "2.43.2"
kotlin = "1.7.10"
ktlint = "11.0.0"

[libraries]
android = { module = "com.android.tools.build:gradle", version.ref = "android" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
dagger-hilt-android-runtime = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }

[plugins]
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
