[versions]
android = "7.2.2"
android-desugar = "1.1.8"
androidx-appcompat = "1.5.1"
androidx-cardview = "1.0.0"
androidx-recyclerview = "1.2.1"
assertj = "2.6.0"
dagger = "2.43.2"
junit = "4.12"
material = "1.6.1"
materialdialogs = "0.9.6.0"
mockito = "3.12.4"
okhttp = "3.9.0"
parceler = "1.1.13"
preference = "28.0.0.0"
retrofit = "2.3.0"
rxandroid = "1.2.1"
rxbinding = "1.0.1"
rxjava = "1.2.7"
rxlifecycle = "1.0"
rxpreferences = "1.0.2"
timber = "4.5.1"

[libraries]
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-desugar" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "androidx-cardview" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
dagger-android-legacy = { module = "com.google.dagger:dagger-android-legacy", version.ref = "dagger" }
dagger-android-support-legacy = { module = "com.google.dagger:dagger-android-support-legacy", version.ref = "dagger" }
dagger-android = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
materialdialogs = { module = "com.afollestad.material-dialogs:core", version.ref = "materialdialogs" }
materialdialogs-commons = { module = "com.afollestad.material-dialogs:commons", version.ref = "materialdialogs" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logginginterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
parceler = { module = "org.parceler:parceler", version.ref = "parceler" }
parceler-api = { module = "org.parceler:parceler-api", version.ref = "parceler" }
preference = { module = "com.takisoft.fix:preference-v7", version.ref = "preference" }
preference-datetimepicker = { module = "com.takisoft.fix:preference-v7-datetimepicker", version.ref = "preference" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-adapter-rxjava = { module = "com.squareup.retrofit2:adapter-rxjava", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
rxandroid = { module = "io.reactivex:rxandroid", version.ref = "rxandroid" }
rxbinding = { module = "com.jakewharton.rxbinding:rxbinding", version.ref = "rxbinding" }
rxbinding-appcompat = { module = "com.jakewharton.rxbinding:rxbinding-appcompat-v7", version.ref = "rxbinding" }
rxjava = { module = "io.reactivex:rxjava", version.ref = "rxjava" }
rxlifecycle = { module = "com.trello:rxlifecycle", version.ref = "rxlifecycle" }
rxlifecycle-components = { module = "com.trello:rxlifecycle-components", version.ref = "rxlifecycle" }
rxpreferences = { module = "com.f2prateek.rx.preferences:rx-preferences", version.ref = "rxpreferences" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
